from tkinter import*
root=Tk()
root.title("My first window")
x=Label(root,text="WELCOME TO K.B.C",bg="red",fg="black",font=("ariel",17))
x.pack()
lavel=Label(root,text="[1]. ham navgurukul me kya sikhte hai",bg="yellow",fg="black",font=("ariel",13))
lavel.pack()
x=Label(root,text="",fg="blue")
x.pack()
root.geometry("400x500+300+150")
# root.resizable(0,0)
# myButton1=Button(root,text="(A)   softwere Enginyearing",bg="blue",padx=10,font=("ariel",10))
# myButton1.pack()
# myButton2=Button(root,text="(B)   softwere Enginyearing",bg="blue",padx=10,font=("ariel",10))
# myButton2.pack()
# myButton3=Button(root,text="(C)   softwere Enginyearing",bg="blue",padx=10,font=("ariel",10))
# myButton3.pack()
# myButton4=Button(root,text="(D)   softwere Enginyearing",bg="blue",padx=10,font=("ariel",10))
# myButton4.pack()
# root.mainloop()